name: hanzo-gateway
services:
- name: gateway
  source_dir: gateway
  github:
    branch: app-platform
    repo: hanzoai/gateway
    deploy_on_push: true
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3001
  routes:
  - path: /
  envs:
  - key: PORT
    value: "3001"
  - key: HOST
    value: "0.0.0.0"
  - key: TRUST_PROXY
    value: "true"
  - key: GATEWAY_IDENTITY
    value: "did:hanzo:gateway"
  - key: DIGITALOCEAN_API_KEY
    value: "sk-do-xwKWq7K46YEhZ_9Qp2NECnqv3Idi048LU93fLXMdgeEHjRGkdmKK-ydh1j"
  - key: VOYAGE_API_KEY
    value: "pa-adPuLsVUbXWfLGVskDbYx5xaggBOG33n0CLKZt60dQS"
  - key: DEEPSEEK_API_KEY
    value: "sk-your_deepseek_key_here"
  - key: OPENAI_API_KEY
    value: "sk-your_openai_key_here"
  - key: ANTHROPIC_API_KEY
    value: "sk-ant-your_anthropic_key_here"
  health_check:
    http_path: /health